### ISSUE TITLE
Wiki编辑权限问题

### ISSUE THREAD

**Issue by davidkhala** [Hyperledger-TWGC/fabric-gm-wiki#1]
不情之请
如果你是TWGC member并且不属于任何TWGC Github teams，请帮忙看一下这个项目的wiki是否可以编辑

**Comment by bjzhang03** [comment]
可以的

**Comment by davidkhala** [comment]
根据Sam的发现，Github wiki现在的权限控制只有两种可以选
一种是仅限project collaborators 
另一种是近乎完全开放，所有持有github id的人员都可以更改wiki，甚至不需要是TWGC member
https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

现在在使用的是开放性权限，个人觉得问题不大，因为这种模式跟现在Confluence wiki的权限是类似的（有LF id就可以编辑）
