### ISSUE TITLE
关于sdk问题讨论的一些记录

### ISSUE THREAD

**Issue by SamYuan1990** [Hyperledger-TWGC/fabric-gm-wiki#2]
关于sdk的问题？
fabric各个版本的sdk分为fabric-gateway-$language和fabric-sdk-$language
然后在实现层面又分为不同的对象 如 wallet接口下 fs wallet

我们可能需要统一的是：
1） 我们国密支持那些语言的sdk？
1.1） 这些语言的优先级？
2） 我们国密支持那个级别的sdk，gateway or sdk
我怕的是这个情况，我们需要在gateway那层的工厂改东西（添加策略gm）。在底层实现策略gm。
3） wallet在内，那些对象我们需要更改？

欢迎大家补充。

**Comment by davidkhala** [comment]
具体的讨论和记录请放在wiki里面
